services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: administracion-qr-app
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped
