services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: administracion-qr-app-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - sistema_relojes_default

networks:
  sistema_relojes_default:
    name: sistema_relojes_default